### ISSUE TITLE
FCS code from photon stamps

### ISSUE THREAD

**Issue by biswajitSM** [tritemio/multispot_paper#1]
Page-57 of Supporting Information contains FCS curves. I was looking for the code that calculates correlation from the photon time stamps in PhotonHDF5. Does the code exist in the repository?

Thanks
Biswajit

**Comment by tritemio** [comment]
Hi @biswajitSM, the FCS computations of the paper is the only one not using FRETBursts and have been performed with a LabVIEW software that can download here (the link is in the SI section2.2):

https://sites.google.com/a/g.ucla.edu/alix/

Unfortunately this software is binary-only and requires MS windows (a labview license is not required though). Under the hood, this labview software uses multi-tau correlation routines implemented by Ted Laurence in C++ (I believe).

It would be useful having on open source implementation that can be used from python. I think a pure python implementation would be straightforward. Ted is interested but so far never found the time to do it. Given the feedback from FRETBursts users, multi-tau correlation routines would be immediately useful to many peoples in the community.

**Comment by biswajitSM** [comment]
Hi @tritemio , Thanks a lot for your quick reply and refs. I came across some python code for correlation code https://github.com/dwaithe/FCS_point_correlator, but need to figure out how to implement it with PhotonHDF5 format.

**Comment by tritemio** [comment]
@biswajitSM, yes I was aware of it but I never used it. Once you load the array from Photon-HDF5 you have a normal numpy array of timestamps. So, you just need to figure out how to use FCS_point_correlator with numpy arrays. I would be interested to know if you succeed. Maybe we can ask the author @dwaithe for an example.

**Comment by tritemio** [comment]
BTW, it would be really nice to have a standalone python package for the log-scaled correlation. If you can make working function I can help with packaging and optimizations.

**Comment by tritemio** [comment]
@biswajitSM, I end up implementing the timestamp correlation in python. I published it in a new package called [pycorrelate](https://pycorrelate.readthedocs.io). I hope it is useful. Let me know if you encounter any issue!

**Comment by biswajitSM** [comment]
Thanks a lot @tritemio ..I am curious to test it..
