### ISSUE TITLE
nbviewer doesn't work on Safari 12.1.1 ?

### ISSUE THREAD

**Issue by smXplorer** [tritemio/multispot_paper#2]
I am trying to view the Jupyter notebooks in the out_notebooks folder and get a blank page with the following cryptic message:

Sorry, something went wrong. Reload?

Any ideas? It seems to work fine on Firefox/Mac according to Maya.

**Comment by tritemio** [comment]
Maybe you mean notebook rendering directly on github? This is spotty and often fails especially with larger notebooks.

[Nbviewer](https://nbviewer.jupyter.org/) is quite reliable instead in my experience. I switch to it anytime a notebook fails to render on github. Here a direct link the out_notebooks folder seen through nbviewer:

https://nbviewer.jupyter.org/github/tritemio/multispot_paper/tree/master/out_notebooks/

**Comment by smXplorer** [comment]
Thanks. Yes, that's what I meant. I was just curious about the Firefox/Safari difference on Macs.
